#
# https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html
#
# name is left out on purpose so these dependencies can be installed to any
# environment using the command line --name option.
#

channels:
  - conda-forge

dependencies:
  - python>=3.7
  - pip:
    - pytest
